### ISSUE TITLE
Error while adding component

### ISSUE THREAD

**Issue by a-mishra-niku** [theroozbeh/vue-tinymce-editor#13]
did npm install vue-tinymce-editor
then trying to hookup 

import tinymce from 'vue-tinymce-editor'
Vue.component('tinymce', tinymce)

give error in ./node_modules/vue-tinymce-editor/src/components/TinymceVue.vue
but compiling works if i change import tinymce from 'vue-tinymce-editor' to import tinymce from 'tinymce' 

compiled success but no editor in console gives app.js:54012 [Vue warn]: Failed to mount component: template or render function not defined. using  "vue-tinymce-editor": "^1.4.4",

**Comment by a-mishra-niku** [comment]
found solution need to install 

npm install --save-dev babel-plugin-transform-runtime and 
"babel-runtime": "^6.26.0"

**Comment by deniszavadskiy** [comment]
@a-mishra-niku  

> change import tinymce from 'vue-tinymce-editor' to import tinymce from 'tinymce'

vue-tinymce-editor using tinymce(JQuery plugin) as it dependencies, so it doesn't solve the issue

**Comment by theroozbeh** [comment]
duplicate of #12
