### ISSUE TITLE
[Error] Something wrong with include font on your package

### ISSUE THREAD

**Issue by tvad911** [theroozbeh/vue-tinymce-editor#14]
I just get a message  as the picture... 
----------------------------------------
http://youtube.dev/fonts/vendor/tinymce/skins/lightgray/tinymce.woff?a7a41ea9358b658ec53e9d042334c1a8 net::ERR_ABORTED
Not found

I think when call, we call from: node_modules/tinymce/.... link to font... 
But i find the url link wrong, i don't know to fix.
----------------------------------------
I'm using Laravel 5.4 and Vuejs2... 
What i need to include to fix it?

![picture139](https://user-images.githubusercontent.com/4197582/33721743-7ade9034-db9a-11e7-8675-dda75f29a18e.jpg)

Thanks

**Comment by tvad911** [comment]
I'm just found the error from tinymce package go with vue-tinymce... I will try to fix...

**Comment by timz** [comment]
hi! this problem in tinymce. add in project "url-loader"
and rule in webpack.config.js:
{
                test: /\.(png|jpg|jpeg|gif|eot|ttf|woff|woff2|svg|svgz)(\?.+)?$/,
                use: [{
                    loader: 'url-loader',
                    options: {
                        limit: 10000
                    }
                }]
            }

**Comment by theroozbeh** [comment]
Sorry for a long delay.
@tvad911  Is this still an issue?

**Comment by theroozbeh** [comment]
Yes this is still an issue and it is duplicate of #19

**Comment by vibrates09** [comment]
@tvad911 did you figure it out?
