### ISSUE TITLE
Internationalization

### ISSUE THREAD

**Issue by dannehl** [theroozbeh/vue-tinymce-editor#3]
It would be awesome if you could support internationalization out of the box. Currently we have to deal with 'language_url' and have i18n packs installed somewhere else in the project.

**Comment by rhajizadeh** [comment]
Yes, I'm aware of that issue and I am working around it to find a solution.

**Comment by theroozbeh** [comment]
Yes, I'm aware of that issue and I am working around it to find a solution. 
Thank you for noticing.

**Comment by theroozbeh** [comment]
After giving it so much though I came to a conclusion that  the best solution for including other languages is using 'language_url'. I also added documentations for this purpose. 
So, I am closing this issue, feel free to reopen it once you have a better solution.
