### ISSUE TITLE
how to use the callback event 

### ISSUE THREAD

**Issue by huangwentai** [theroozbeh/vue-tinymce-editor#4]
how to use the callback event ,like onchange, oninit. and vue first time value is not bind

**Comment by theroozbeh** [comment]
Right now it is not possible to use these callbacks.
I will fix it in near future.

**Comment by grantmooney** [comment]
Hey rhajizadeh, take a look at my fork - I've added support for these callbacks using @init_callback events to the component

**Comment by theroozbeh** [comment]
Now listening for call back events are possible
please upgrade to the latest version and follow documents

**Comment by xiaomizhou66** [comment]
how to use Blur event
