### ISSUE TITLE
Vue js editor content not loading when in modal

### ISSUE THREAD

**Issue by jignesh-levaral** [theroozbeh/vue-tinymce-editor#5]
I am using this component, with normal and in modal, but it is not working with modal, the value of field/ modal not set or bind

**Comment by theroozbeh** [comment]
I will test this and fix it in next release

**Comment by huangwentai** [comment]
@jignesh-levaral i know this issue, maybe the tinimce vesion is update , it cause TinymceVue.vue  editor.on('init', (e) => function is no working , so you can move insite the code to outside, it bind . and there is a tip , if you use modal like element ui , 'append-to-body' make it broken, you are welcome

**Comment by kristoff2016** [comment]
Hi any update on status this issue ?

**Comment by theroozbeh** [comment]
Hi
I hope it is not too late 
@jignesh-levaral how are you the creating modal element?

**Comment by lumin824** [comment]
@jignesh-levaral 
i solve this problem in element-ui dialog 
`@editorInit="e => e.setContent(/* init value*/)"`

**Comment by ezhimakov** [comment]
Oh, thanks, guys, killed 3 hours to find what is the point of bug.

**Comment by theroozbeh** [comment]
OK then. I'm closing this issue
