### ISSUE TITLE
Working with codesample plugin tinymce incorrect

### ISSUE THREAD

**Issue by phambinh217** [theroozbeh/vue-tinymce-editor#6]
When in insert a code sample, it working well. But i can not update it.
example:
I insert code bellow by codesample plugin tinymce
`<?php echo 'Hello world' ?>`
Then, I change it to
`<?php echo 'Hello world 123' ?>`
It not change. Please help me.
Sorry bad english

**Comment by theroozbeh** [comment]
Can you please explain your problem a little more?
perhaps if you could send a little more of your code.

**Comment by phambinh217** [comment]
I am sorry.
Your demo https://dyonir.github.io/vue-tinymce-editor/
Can you install tinymce's plugin codesample?
It here: https://www.tinymce.com/docs/plugins/codesample/
