### ISSUE TITLE
ReferenceError: Unknown plugin "transform-runtime"

### ISSUE THREAD

**Issue by Suruat** [theroozbeh/vue-tinymce-editor#7]
Error appears on webpack build. I guess it's about some babel  update

**Comment by tartinesKiller** [comment]
Resolved it with the following package install:
npm install --save-dev babel-plugin-transform-runtime

**Comment by Suruat** [comment]
But shouldn't it be in editor's dependencies?

**Comment by tartinesKiller** [comment]
It should, I've just opened an issue (#12) about this

**Comment by Suruat** [comment]
Thank you for response. I've hope plugin's authors are still supporting it.

**Comment by theroozbeh** [comment]
duplicate of #12
